spring.application.name=orderms

spring.data.mongodb.auto-index-creation=true

spring.mongodb.authentication-database=admin
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=btgpactualdb
spring.mongodb.username=admin
spring.mongodb.password=123


#Estou usando Spring Boot 4.0.6. No Boot 4, várias configs do Mongo mudaram de:
#
#spring.data.mongodb.*
#para:
#
#spring.mongodb.*


#spring.application.name=orderms
#
#spring.data.mongodb.authentication-database=admin
#spring.data.mongodb.auto-index-creation=true
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=btgpactualdb
#spring.data.mongodb.username=admin
#spring.data.mongodb.password=123